name: ca_mobile
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.1+11

environment:
  sdk: ^3.6.0

dependencies:
  animated_bottom_navigation_bar: ^1.3.3
  bloc: ^9.0.0
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.4
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  grouped_list: ^6.0.0
  image_picker: ^1.1.2
  # internet_connection_checker_plus: ^2.7.1
  intl: 
  package_info_plus: ^8.1.3
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  shared_preferences: ^2.4.0
  shimmer_animation: ^2.2.2
  smooth_page_indicator: ^1.2.0+3
  banca_movil_libs:
    path: ../banca_movil_libs
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

## dart run flutter_native_splash:create
flutter_native_splash:
  color: "#005199"
  # color: "#ffffff"
  image: assets/images/logo-splash.png
  fullscreen: true
  android_12:
    # Splash screen background color.
    color: "#005199"
    # color: "#ffffff"
    image: assets/images/logo-splash.png

# After set, run: dart run flutter_launcher_icons -f AppIcon
flutter_icons:
  android: true
  remove_alpha_ios: true
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    
