name: banca_movil_libs
description: "A new Flutter package project."
version: 0.0.1
# homepage:

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  intl: #^0.20.2
  google_fonts: ^6.2.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  shared_preferences: ^2.4.0
  flutter_localizations:
    sdk: flutter
  internet_connection_checker_plus: ^2.7.1
  local_auth: ^2.3.0
  flutter_secure_storage: ^9.2.4
  encrypt: ^5.0.3

  fphi_sdkmobile_core:
    hosted:
      name: fphi_sdkmobile_core
      url: https://facephicorp.jfrog.io/artifactory/api/pub/pub-pro-fphi/
    version: ^2.0.0

  fphi_sdkmobile_selphi:
    hosted:
      name: fphi_sdkmobile_selphi
      url: https://facephicorp.jfrog.io/artifactory/api/pub/pub-pro-fphi/
    version: ^2.2.0
  fphi_sdkmobile_selphid:
    hosted:
      name: fphi_sdkmobile_selphid
      url: https://facephicorp.jfrog.io/artifactory/api/pub/pub-pro-fphi/
    version: ^2.2.0
  dartz: ^0.10.1

  crypto: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
